### ISSUE TITLE
Inquiry Regarding `kmnc_profile` Contents and DiffChaser Command

### ISSUE THREAD

**Issue by Davidjinzb** [youhanmo/DRFuzz#1]
Dear Hanmo,

While attempting to replicate your work, we encountered an issue that we hope you can assist us with. Specifically, during our setup process, we came across an error related to the `kmnc_profile` folder. It appears that we are missing the `cifar10_vgg16_p80` content within this directory.

Could you kindly provide the contents of `cifar10_vgg16_p80` located in the `kmnc_profile` folder, or guide us on how to generate or obtain it correctly? Your assistance in this matter would greatly facilitate our progress and enable a smoother replication process.

Additionally, Could you please share the specific command or instructions on how to deploy DiffChaser?

Thank you very much for your time and assistance.

**Comment by youhanmo** [comment]
Dear Jinbo,
I have already provided you with the link for the files in the kmnc profile directory. Please refer to the ‘Extra File’ Section in the latest readme file.

For DiffChaser, I've helped you contacting with the author for deploying DiffChaser (in the email). Please feel free to find him. :)

**Comment by WingedVampires** [comment]
Dear Jinbo,
The command which we used to deploy DIffChaser is as follow:
`python DiffTesting.py -i seeds/ -o output -type cifar10 -model_type vgg16 -model1 m1.hdf5 -model2 m2.h5 -max_iteration 100`

**Comment by youhanmo** [comment]
Since we have already provided the link in the 'Extra Files' section of the latest README file, we have decided to close this issue. Thank you for taking the time to familiarize yourself with our work.
